### 회원 가입
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "email": {
    "value": "jonguk1221@gmail.com"
  },
  "name": {
    "first": "jonguk",
    "last": "park"
  },
  "password": {
    "value": "complicated"
  }
}

### 조회
GET http://localhost:8080/api/members/1

### 비밀번호 변경
PUT http://localhost:8080/api/members/1/password
Content-Type: application/json

{
  "password": {
    "value": "old",
    "newValue": "new"
  }
}

### 삭제
DELETE http://localhost:8080/api/members/1